name: ass-workflow
on:
  pull_request:
    branches:
      - "main"

jobs:
  first-job:
  runs-on: ubuntu-latest
  steps:
    - name: checkout
      uses: actions/checkout@v4

    - name: clean mvn
      run: mvn clean package
      shell: bash