# name: ass workflow
# on:
# name: ass workflow
# on:
#   repository_dispatch:
#   types: [build]

# jobs:
#   first-workflow-job:
#     runs-on: ubuntu-latest
#     steps:

#       - name: chechout
#         uses: actions/checkoutv4

#       - name: run maven
#         run: mvn clean package
#         shell: bash 
